### PR TITLE
Endpoint.js: clear cookie interval on destroy (fixes #11)

### LINKED ISSUE #11: How to really close sctpSocket
By creating some unit tests (SCTP over plain UDP, in both UDP unconnected and connected mode in Node >= 12), I'm realizing that once `sctpSocket = sctp.connect()` is called, the test script cannot exit because, somehow, some handler remains active.

I'm closing the `udpSocket` I provide `sctp.connect()` with, and also trying to "terminate" the `sctpSocket` by calling `end()` on it when the test ends, also `destroy()`. Nothing works. It looks like if some internal timer within node-sctp (probably stuff doing the INIT ACK exchange) remains working inside and it's not terminated.

Any thoughts?

### PR DESCRIPTION
**Pull request by ibc**

### CODE REVIEW

**Comment by ibc** [comment]
Thanks :)
Will you release a new NPM version?

**Comment by latysheff** [comment]
Already! And thank you too)

**Comment by ibc** [comment]
Great, thanks :)

**Comment by ibc** [comment]
BTW it would be great if the README mentions that the app must call `sctpSocket.end()` when it wants to close it and its internal resources and handles.

**Pull request merged**
